[build]
  command = "cd frontend && npm install && npm run build && echo '/* /index.html 200' > dist/_redirects"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
